### ISSUE TITLE
java.lang.Float cannot be cast to java.lang.Double

### ISSUE THREAD

**Issue by pavelperc** [dburckh/bitmap2video#15]
Get this exception on Android 5 emulator:
```
java.lang.ClassCastException: java.lang.Float cannot be cast to java.lang.Double
        at android.media.MediaCodecInfo$VideoCapabilities.supportsFormat(MediaCodecInfo.java:1016)
        at android.media.MediaCodecInfo$CodecCapabilities.isFormatSupported(MediaCodecInfo.java:335)
        at android.media.MediaCodecList.findCodecForFormat(MediaCodecList.java:218)
        at android.media.MediaCodecList.findEncoderForFormat(MediaCodecList.java:207)
        at com.homesoft.encoder.FrameBuilder.<init>(FrameBuilder.kt:61)
```

**Comment by pavelperc** [comment]
Actually because of this line:
https://github.com/AndroidSDKSources/android-sdk-sources-for-api-level-21/blob/master/android/media/MediaCodecInfo.java#L1016
